In [9]:
import numpy as np
x = np.random.randn(5, 5) + 10
print(x.shape)
print(x)

(5, 5)
[[11.41901708  8.98038847  9.9136511  10.47491492 10.20423993]
 [ 8.44653628  9.3392423  10.19361921  8.9991123   8.33010574]
 [ 7.92098558  9.95857388 10.24878909 10.77963452 11.06022581]
 [ 9.2638739   8.6868619   8.5622497   9.88305087  9.41465553]
 [ 9.23858635 10.3285053   9.5785747  10.19387549  9.48403036]]


In [10]:
p = 0.5
mask = np.random.rand(*x.shape)
print(mask)
print(np.random.rand(*x.shape) < p)
mask = (np.random.rand(*x.shape) < p) /p
print(mask.shape)
print(mask)
print(x*mask)

[[0.65059186 0.20306567 0.52650442 0.49173079 0.47966827]
 [0.85447973 0.21357461 0.59206344 0.25280663 0.43612172]
 [0.259983   0.47850925 0.37150236 0.06047511 0.03109046]
 [0.36793396 0.35935672 0.19852339 0.7826409  0.77569022]
 [0.65071244 0.49320023 0.6593232  0.2999735  0.98413339]]
[[False  True  True False False]
 [ True  True  True False False]
 [False False False  True  True]
 [ True  True  True False  True]
 [False False False  True False]]
(5, 5)
[[0. 2. 0. 2. 2.]
 [2. 0. 2. 0. 0.]
 [0. 0. 0. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 0. 2. 0.]]
[[ 0.         17.96077694  0.         20.94982983 20.40847985]
 [16.89307257  0.         20.38723843  0.          0.        ]
 [ 0.          0.          0.         21.55926903 22.12045162]
 [18.5277478  17.3737238  17.1244994  19.76610173 18.82931105]
 [18.4771727  20.6570106   0.         20.38775098  0.        ]]
